# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# Only manual triggers
trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

#resources:
#  pipelines:
#    - pipeline: medaBom
#      source: pagopa.meda-bom.meda-bom.deploy
#      trigger:
#        branches:
#          include:
#            - master
#            - release
#            - features/*
#            - feature/*
steps:
  - task: DownloadSecureFile@1
    displayName: 'download settings.xml for Maven'
    name: settingsxml
    inputs:
      secureFile: 'settings-rw.xml'
      retryCount: '2'
  - task: MavenAuthenticate@0
    displayName: 'Maven Authenticate'
    inputs:
     MavenServiceConnections: cstar
  - task: Maven@3
    displayName: Build and Deploy Artifacts
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'deploy'
      options: '-s $(settingsxml.secureFilePath) -DaltDeploymentRepository=cstar::default::https://pkgs.dev.azure.com/pagopaspa/cstar-projects/_packaging/cstar/maven/v1'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      mavenVersionOption: 'Default'
      mavenOptions: '-Xmx3072m'
      mavenAuthenticateFeed: true
      effectivePomSkip: true
      sonarQubeRunAnalysis: false